improved validation in driver factory
helderjs/doctrine-mongo-odm pull request #4
Opened 2018-05-03 17:13 UTC by vinaocruz

Correção das factories dos drivers Annotations, Yaml e Xml quando na configuração é informado um array vazio. Os testes com configuração vazia falhavam

2018-05-03 17:47 UTC, vinaocruz commented
Temos um problema de dependências em cascata. Veja:
- Este projeto tem depende de "doctrine/mongodb-odm": "^1.2"
- O doctrine/mongodb-odm:1.2 depende de "doctrine/annotations": "~1.2" (ou seja, >=1.2 <2.0.0)
- Já o doctrine/annotations: 1.6 requer php: ^7.1

Este é uma das causas para o erro no teste com php5.6:
https://github.com/doctrine/annotations/blob/1.5/lib/Doctrine/Common/Annotations/AnnotationRegistry.php#L50

2018-05-04 08:57 UTC, helderjs requested changes

2018-05-04 08:57 UTC, helderjs commented on src/AnnotationDriverFactory.php
> +        if (empty($options[AnnotationDriver::class])) {
Aqui e na outras checagens, seria melhor manter o nome da chave como descrito no exemplo de configuraçao.
Nao que seja má idéia, porém:

1) Mantém compatibilidade com a versao atual (quem atualizar, nao precisar alterar configuraçoes)
2) Fica mais fácil (e menos verboso) suportar novos formatos de configuraçao (yaml, xml...)

2018-05-04 08:57 UTC, helderjs commented on composer.json
> +      "ext-mongo": "1.6.16"
Para quem (infelizmente) ainda usa php5, vc nao estaria escondendo essa dependencia com essa configuraçao?

2018-05-04 13:15 UTC, vinaocruz commented on composer.json
> +      "ext-mongo": "1.6.16"
Tem razão. Esqueci de retirar enquanto commitava.

2018-05-04 13:34 UTC, helderjs commented
@matwright Why did you merge this PR into your PR? could please revert this?

2018-05-04 13:36 UTC, matwright commented
@helderjs because I received a pull request. There was a minor conflict in the composer file. 
Did you send a PR to the wrong branch/fork?

2018-05-04 13:40 UTC, matwright commented
@helderjs I've reverted the merge. Do I need to do anything else?

2018-05-04 13:42 UTC, helderjs commented
@matwright That's strage. I'm still seeing both PR merged into each other. We need to revert these changes to do a proper merge o master.

2018-05-04 13:59 UTC, helderjs commented
@matwright and @vinaocruz I really don't know what happened here. So I going to merge this PR and close the https://github.com/helderjs/doctrine-mongo-odm/pull/3. Before create a new release I'll do some checks to avoid BC breaks.

2018-05-04 14:10 UTC, merged